# Generated by Django 5.2.1 on 2025-05-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_student_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
